services:
  database:
    image: 'postgres:latest'
    ports:
      - '5432:5432'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_DB=postgres'
      - 'POSTGRES_PASSWORD=3632'
    volumes:
      - './volumes/codecake-yt/postgres:/var/lib/postgresql/data'
